# Generated by Django 4.2.16 on 2026-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
