# Generated by Django 4.2.16 on 2026-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersession_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofa_method',
            field=models.CharField(blank=True, choices=[('totp', 'TOTP'), ('sms', 'SMS')], default='totp', max_length=10),
        ),
    ]
