# Generated by Django 4.2.16 on 2026-02-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition_type', models.CharField(choices=[('anomaly_count', 'Anomaly Count Exceeds'), ('failed_logins', 'Failed Login Attempts'), ('error_rate', 'Error Rate Exceeds'), ('honeypot_access', 'Honeypot Access Detected')], max_length=50)),
                ('threshold', models.FloatField(default=0)),
                ('action', models.CharField(choices=[('email', 'Send Email'), ('telegram', 'Send Telegram'), ('notification', 'In-App Notification'), ('all', 'All Channels')], default='notification', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
