# Generated by Django 4.2.16 on 2026-02-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='is_e2e_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConfessionEncryptedKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_key', models.TextField()),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_keys', to='confessions.confession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_encrypted_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('confession', 'user')},
            },
        ),
    ]
