# Generated by Django 4.2.16 on 2026-02-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='last_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='model_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='threshold',
            field=models.FloatField(default=-0.5),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='training_samples_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL),
        ),
    ]
