# Generated by Django 4.2.16 on 2026-03-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='actlog_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='actlog_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['response_status'], name='actlog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['request_method'], name='actlog_method_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelconfig',
            index=models.Index(fields=['model_type', 'is_active'], name='aiconfig_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyreport',
            index=models.Index(fields=['-detected_at'], name='anomaly_detected_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyreport',
            index=models.Index(fields=['user', 'detected_at'], name='anomaly_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyreport',
            index=models.Index(fields=['severity'], name='anomaly_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyreport',
            index=models.Index(fields=['is_resolved'], name='anomaly_resolved_idx'),
        ),
    ]
