# Generated by Django 4.2.16 on 2026-02-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_document_category_document_security_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_e2e_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentEncryptedKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_key', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_keys', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_encrypted_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user')},
            },
        ),
    ]
