# Generated by Django 4.2.16 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_iv',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
