# Generated by Django 4.2.16 on 2026-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_file_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshare',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
